"use client";

import { useState, useEffect, use, useRef } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { TrendingUp, Plus, Trash2, MessageCircle } from "lucide-react";
import { fetchSession, refineWithGaps, generatePDF, ApiError, reanalyzeGaps } from "@/lib/api";
import type { SessionDetail } from "@/types/session";

// ── Gap Types & Helpers ───────────────────────────────────────────────────────

export type GapMode = "skill" | "experience" | "project";

export interface ExperienceEntry {
  company: string;
  jobTitle: string;
  startDate: string;
  endDate: string;
  description: string;
}

export interface GapAnswer {
  mode: GapMode;
  // skill gap
  hasExperience?: boolean | 'ai_generate';
  skillNote?: string;
  placementMode?: 'skill' | 'project_or_exp' | 'summary';
  projectType?: 'existing' | 'new' | 'skill';
  attachToExisting?: string; // name of existing project or company to attach skill note to
  projectName?: string;
  projectTech?: string;
  projectDescription?: string;
  projectUrl?: string;
  generateProject?: boolean;
  // follow-up clarification (set by AI)
  pendingQuestion?: string;
  pendingOptions?: string[];
  clarificationAnswer?: string;
}

function detectGapMode(_gap: string): GapMode {
  // All gaps in the card are skill-only now; experience/project are standalone sections
  return "skill";
}

function serializeGapAnswer(gap: string, answer: GapAnswer): string {
  if (answer.hasExperience === 'ai_generate') {
    const skill = gap.split(":")[0] || gap.split("—")[0] || "this skill";
    return `GENERATE_PROJECT: ${skill} | Description: Built a project demonstrating knowledge of ${skill} (Generated by AI).`;
  }

  if (answer.placementMode === 'summary') {
    let note = answer.skillNote || "";
    if (answer.clarificationAnswer) note += ` | Clarification: ${answer.clarificationAnswer}`;
    return `ADD_TO_SUMMARY: ${note}`;
  }
  
  // Project / Experience mode (or default)
  if (!answer.placementMode || answer.placementMode === 'project_or_exp' || answer.placementMode === 'skill') {
    // New project
    if (answer.projectType === 'new') {
      const skill = gap.split(":")[0] || gap.split("—")[0] || "this skill";
      let text = `GENERATE_PROJECT: ${skill} `;
      if (answer.projectName) text += `| Name: ${answer.projectName} `;
      if (answer.projectDescription) text += `| Description: ${answer.projectDescription} `;
      if (answer.projectUrl) text += `| URL: ${answer.projectUrl} `;
      if (answer.skillNote) text += `| User Knowledge: ${answer.skillNote}`;
      return text.trim();
    }
    
    // Existing project
    if (answer.projectType === 'existing' || !answer.projectType || answer.projectType === 'skill') {
      const pName = answer.attachToExisting?.trim();
      if (!pName) return answer.skillNote || "";
      let text = `ADD_TO_PROJECT: ${pName} `;
      if (answer.projectTech) text += `(Tech: ${answer.projectTech}) `;
      if (answer.projectDescription) text += `— ${answer.projectDescription} `;
      if (answer.skillNote) text += `| User Knowledge: ${answer.skillNote}`;
      return text.trim();
    }
  }
  
  return answer.skillNote || "";
}

function serializeExperienceEntry(e: ExperienceEntry): string {
  if (!e.company && !e.description) return "";
  let line = "";
  if (e.company) line += `Company: ${e.company}`;
  if (e.jobTitle) line += ` | Role: ${e.jobTitle}`;
  if (e.startDate) line += ` | From: ${e.startDate}`;
  if (e.endDate) line += ` to ${e.endDate}`;
  if (e.description) line += `\nDetails: ${e.description}`;
  return line.trim();
}

function serializeProjectEntry(p: ProjectEntry): string {
  if (!p.name && !p.description && !p.tech) return "";
  if (p.generateWithAI) {
    return `GENERATE_PROJECT: ${p.tech} | Name: ${p.name || 'Basic Project'}`;
  }
  let line = "project: " + (p.name || "");
  if (p.tech) line += ` (Tech: ${p.tech})`;
  if (p.description) line += ` — ${p.description}`;
  if (p.url) line += ` | URL: ${p.url}`;
  return line.trim();
}

// ── ScoreComparisonBanner ──────────────────────────────────────────────────────

function ScoreGauge({ label, score, projected, color }: { label: string; score: number | null; projected: number; color: string }) {
  const orig = score ?? 0;
  const gain = projected - orig;
  return (
    <div className="flex-1 min-w-[140px] bg-slate-800/60 border border-slate-700 rounded-xl p-4">
      <p className="text-zinc-500 text-xs font-semibold uppercase tracking-widest mb-3">{label}</p>
      <div className="flex items-end gap-3">
        {/* Original */}
        <div className="text-center">
          <div className={`text-3xl font-bold ${orig < 50 ? 'text-red-400' : orig < 70 ? 'text-amber-400' : 'text-emerald-400'}`}>
            {score !== null ? orig : '—'}
          </div>
          <p className="text-zinc-600 text-[10px] mt-1">Original</p>
        </div>
        {/* Arrow */}
        <TrendingUp size={18} className={`mb-2 ${color} shrink-0`} />
        {/* Projected */}
        <div className="text-center">
          <div className={`text-3xl font-bold ${color}`}>{projected}</div>
          <p className="text-zinc-600 text-[10px] mt-1">Projected</p>
        </div>
      </div>
      {gain > 0 && (
        <div className={`mt-3 inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full ${color} bg-current/10`}>
          <span className="opacity-80">↑ +{gain} pts after upgrade</span>
        </div>
      )}
    </div>
  );
}

function ScoreComparisonBanner({
  session,
  selectedImprovementsCount,
  addressedGapsCount,
  totalGapsCount,
}: {
  session: SessionDetail;
  selectedImprovementsCount: number;
  addressedGapsCount: number;
  totalGapsCount?: number;
}) {
  const ea = session.enhanced_analysis;
  const origMatch = ea?.match_score ?? null;
  const origAts = ea?.ats_score ?? null;

  const totalImprovements = ea?.improvements?.length || 0;
  const totalGaps = totalGapsCount ?? (ea?.gaps?.length || 0);

  // Projected score: purely proportional to actions taken
  // ATS: each terminology improvement checked = proportional share of missing ATS points
  const atsGain = totalImprovements > 0
    ? Math.round((selectedImprovementsCount / totalImprovements) * Math.max(0, 100 - (origAts ?? 0)) * 0.85)
    : 0;

  // Match: each gap addressed = proportional share of missing match points
  const matchGain = totalGaps > 0
    ? Math.round((addressedGapsCount / totalGaps) * Math.max(0, 100 - (origMatch ?? 0)) * 0.85)
    : 0;

  // Projected improvements
  const projMatch = Math.min(100, (origMatch ?? 40) + matchGain);
  const projAts = Math.min(100, (origAts ?? 55) + atsGain);

  return (
    <div className="bg-slate-900/80 border border-slate-700/60 rounded-2xl p-5 mb-2 transition-all duration-300">
      <div className="flex items-center gap-2 mb-4">
        <TrendingUp size={16} className="text-indigo-400" />
        <p className="text-zinc-300 text-sm font-semibold">Live Score Projection</p>
        <span className="text-zinc-600 text-xs ml-1 hidden sm:inline">— dynamically updates as you select improvements and address gaps</span>
      </div>
      <div className="flex flex-wrap gap-4">
        <ScoreGauge label="JD Match Score" score={origMatch} projected={projMatch} color="text-indigo-400" />
        <ScoreGauge label="ATS Score" score={origAts} projected={projAts} color="text-emerald-400" />
      </div>
    </div>
  );
}

// ── SmartGapCard ──────────────────────────────────────────────────────────────

// ── SmartGapCard (skill/knowledge only) ──────────────────────────────────────
// Work Experience and Projects are handled in their own top-level sections above.

function SmartGapCard({
  index,
  gap,
  answer,
  onChange,
  existingEntities = [],
}: {
  index: number;
  gap: string;
  answer: GapAnswer;
  onChange: (index: number, answer: GapAnswer) => void;
  existingEntities?: string[];
}) {
  const update = (patch: Partial<GapAnswer>) => onChange(index, { ...answer, ...patch });

  const gapTitle = gap.split("—")[0].trim();
  const gapDetail = gap.includes("—") ? gap.split("—").slice(1).join("—").trim() : "";

  return (
    <div className="bg-slate-800/50 border border-slate-700 rounded-xl overflow-hidden">
      {/* Gap header */}
      <div className="flex items-start gap-3 p-4 border-b border-slate-700/60">
        <span className="mt-1 shrink-0 w-5 h-5 rounded-full bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-400 text-xs font-bold">!</span>
        <div>
          <p className="text-zinc-100 text-sm font-medium leading-snug">{gapTitle}</p>
          {gapDetail && <p className="text-zinc-500 text-xs mt-1 leading-relaxed">{gapDetail}</p>}
        </div>
      </div>

      <div className="p-4 space-y-3">
        <div className="flex flex-col sm:flex-row sm:items-center gap-3 bg-slate-900/60 p-4 rounded-xl border border-slate-700/50 shadow-inner">
          <span className="text-sm font-medium text-zinc-300 shrink-0">Do you have any knowledge of this?</span>
          <div className="flex flex-wrap gap-3 sm:ml-auto">
            <label className={`group relative flex items-center gap-2.5 px-3 py-2 rounded-lg cursor-pointer transition-colors ${answer.hasExperience === true ? "bg-indigo-500/10" : "hover:bg-slate-800"}`}>
              <input type="radio" name={`skill-exp-${index}`} className="peer sr-only"
                checked={answer.hasExperience === true}
                onChange={() => update({ hasExperience: true, placementMode: 'project_or_exp', projectType: 'existing', generateProject: false })} />
              <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center transition-all ${answer.hasExperience === true ? "border-indigo-400" : "border-slate-500 group-hover:border-indigo-400"}`}>
                <div className={`w-2 h-2 rounded-full bg-indigo-400 transition-transform ${answer.hasExperience === true ? "scale-100" : "scale-0"}`} />
              </div>
              <span className={`text-sm font-medium transition-colors ${answer.hasExperience === true ? "text-indigo-300" : "text-zinc-400 group-hover:text-zinc-200"}`}>Yes</span>
            </label>
            <label className={`group relative flex items-center gap-2.5 px-3 py-2 rounded-lg cursor-pointer transition-colors ${answer.hasExperience === false ? "bg-indigo-500/10" : "hover:bg-slate-800"}`}>
              <input type="radio" name={`skill-exp-${index}`} className="peer sr-only"
                checked={answer.hasExperience === false}
                onChange={() => update({ hasExperience: false, skillNote: "", attachToExisting: "" })} />
              <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center transition-all ${answer.hasExperience === false ? "border-indigo-400" : "border-slate-500 group-hover:border-indigo-400"}`}>
                <div className={`w-2 h-2 rounded-full bg-indigo-400 transition-transform ${answer.hasExperience === false ? "scale-100" : "scale-0"}`} />
              </div>
              <span className={`text-sm font-medium transition-colors ${answer.hasExperience === false ? "text-indigo-300" : "text-zinc-400 group-hover:text-zinc-200"}`}>No</span>
            </label>
            <label className={`group relative flex items-center gap-2.5 px-3 py-2 rounded-lg cursor-pointer transition-colors ${answer.hasExperience === 'ai_generate' ? "bg-emerald-500/10 ring-1 ring-emerald-500/30" : "hover:bg-slate-800"}`}>
              <input type="radio" name={`skill-exp-${index}`} className="peer sr-only"
                checked={answer.hasExperience === 'ai_generate'}
                onChange={() => update({ hasExperience: 'ai_generate', generateProject: true })} />
              <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center transition-all ${answer.hasExperience === 'ai_generate' ? "border-emerald-400" : "border-slate-500 group-hover:border-emerald-400"}`}>
                <div className={`w-2 h-2 rounded-full bg-emerald-400 transition-transform ${answer.hasExperience === 'ai_generate' ? "scale-100" : "scale-0"}`} />
              </div>
              <span className={`text-sm font-medium transition-colors ${answer.hasExperience === 'ai_generate' ? "text-emerald-400" : "text-emerald-500/70 group-hover:text-emerald-400"}`}>✨ Generate Project</span>
            </label>
          </div>
        </div>

        {answer.hasExperience === true && (
          <div className="space-y-4 pt-2 animate-in fade-in slide-in-from-top-2 duration-300">
            
            {/* 1. Placement Selection */}
            <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-4 space-y-4 shadow-sm">
              <p className="text-xs text-zinc-400 font-semibold uppercase tracking-wider">Placement Configuration</p>
              
              <div className="flex flex-col gap-3">
                <div className="flex flex-wrap gap-4">
                  <label className={`group flex items-center gap-2 cursor-pointer p-2 -m-2 rounded-lg transition-colors ${answer.placementMode === 'summary' ? "bg-indigo-500/5" : "hover:bg-slate-800/50"}`}>
                    <div className="relative flex items-center justify-center w-4 h-4">
                      <input type="radio" name={`place-mode-${index}`} className="peer sr-only"
                        checked={answer.placementMode === 'summary'} 
                        onChange={() => update({ placementMode: 'summary' })} />
                      <div className={`w-full h-full rounded-full border-2 flex items-center justify-center transition-all ${answer.placementMode === 'summary' ? "border-indigo-400" : "border-slate-500 group-hover:border-indigo-400"}`}>
                        <div className={`w-2 h-2 rounded-full bg-indigo-400 transition-transform ${answer.placementMode === 'summary' ? "scale-100" : "scale-0"}`} />
                      </div>
                    </div>
                    <span className={`text-sm transition-colors ${answer.placementMode === 'summary' ? "text-indigo-300 font-medium" : "text-zinc-300"}`}>Add to Summary</span>
                  </label>
                  <label className={`group flex items-center gap-2 cursor-pointer p-2 -m-2 rounded-lg transition-colors ${(!answer.placementMode || answer.placementMode === 'project_or_exp') ? "bg-indigo-500/5" : "hover:bg-slate-800/50"}`}>
                    <div className="relative flex items-center justify-center w-4 h-4">
                      <input type="radio" name={`place-mode-${index}`} className="peer sr-only"
                        checked={!answer.placementMode || answer.placementMode === 'project_or_exp'} 
                        onChange={() => update({ placementMode: 'project_or_exp', projectType: answer.projectType || 'existing' })} />
                      <div className={`w-full h-full rounded-full border-2 flex items-center justify-center transition-all ${(!answer.placementMode || answer.placementMode === 'project_or_exp') ? "border-indigo-400" : "border-slate-500 group-hover:border-indigo-400"}`}>
                        <div className={`w-2 h-2 rounded-full bg-indigo-400 transition-transform ${(!answer.placementMode || answer.placementMode === 'project_or_exp') ? "scale-100" : "scale-0"}`} />
                      </div>
                    </div>
                    <span className={`text-sm transition-colors ${(!answer.placementMode || answer.placementMode === 'project_or_exp') ? "text-indigo-300 font-medium" : "text-zinc-300"}`}>Add to Skills / Projects</span>
                  </label>
                </div>

                {(!answer.placementMode || answer.placementMode === 'project_or_exp') && (
                  <div className="pl-6 space-y-3 border-l-2 border-indigo-500/20 mt-1 pt-2 animate-in fade-in slide-in-from-left-2 duration-300">
                    <div className="flex flex-wrap items-center gap-5">
                      <label className={`group flex items-center gap-2 cursor-pointer p-1.5 -m-1.5 rounded-lg transition-colors ${(!answer.projectType || answer.projectType === 'existing' || answer.projectType === 'skill') ? "" : "hover:bg-slate-800/50"}`}>
                        <div className="relative flex items-center justify-center w-3.5 h-3.5">
                          <input type="radio" name={`proj-type-${index}`} className="peer sr-only"
                            checked={!answer.projectType || answer.projectType === 'existing' || answer.projectType === 'skill'} 
                            onChange={() => update({ projectType: 'existing', generateProject: false })} />
                          <div className={`w-full h-full rounded-full border-2 flex items-center justify-center transition-all ${(!answer.projectType || answer.projectType === 'existing' || answer.projectType === 'skill') ? "border-indigo-400" : "border-slate-500 group-hover:border-indigo-400"}`}>
                            <div className={`w-1.5 h-1.5 rounded-full bg-indigo-400 transition-transform ${(!answer.projectType || answer.projectType === 'existing' || answer.projectType === 'skill') ? "scale-100" : "scale-0"}`} />
                          </div>
                        </div>
                        <span className={`text-xs transition-colors ${(!answer.projectType || answer.projectType === 'existing' || answer.projectType === 'skill') ? "text-indigo-300 font-medium" : "text-zinc-400 group-hover:text-zinc-300"}`}>Existing Project / Job</span>
                      </label>
                      <label className={`group flex items-center gap-2 cursor-pointer p-1.5 -m-1.5 rounded-lg transition-colors ${answer.projectType === 'new' ? "" : "hover:bg-slate-800/50"}`}>
                        <div className="relative flex items-center justify-center w-3.5 h-3.5">
                          <input type="radio" name={`proj-type-${index}`} className="peer sr-only"
                            checked={answer.projectType === 'new'} 
                            onChange={() => update({ projectType: 'new' })} />
                          <div className={`w-full h-full rounded-full border-2 flex items-center justify-center transition-all ${answer.projectType === 'new' ? "border-indigo-400" : "border-slate-500 group-hover:border-indigo-400"}`}>
                            <div className={`w-1.5 h-1.5 rounded-full bg-indigo-400 transition-transform ${answer.projectType === 'new' ? "scale-100" : "scale-0"}`} />
                          </div>
                        </div>
                        <span className={`text-xs transition-colors ${answer.projectType === 'new' ? "text-indigo-300 font-medium" : "text-zinc-400 group-hover:text-zinc-300"}`}>New Project</span>
                      </label>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* 2. Content Inputs */}
            
            {answer.placementMode === 'summary' && (
              <textarea
                value={answer.skillNote || ""}
                onChange={(e) => update({ skillNote: e.target.value })}
                placeholder="Describe what you know about this. Be specific — the AI will turn this into a resume bullet using JD keywords."
                rows={2}
                className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors"
              />
            )}

            {answer.placementMode === 'project_or_exp' && answer.projectType === 'existing' && (
              <div className="space-y-3 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                <div>
                  <p className="text-xs text-zinc-400 mb-1">Project / Job Name <span className="text-rose-400">*</span></p>
                  {existingEntities && existingEntities.length > 0 ? (
                    <div className="space-y-2">
                      <select
                        value={existingEntities.includes(answer.attachToExisting || "") ? answer.attachToExisting : (answer.attachToExisting ? "Other..." : "")}
                        onChange={(e) => {
                          if (e.target.value === "Other...") {
                            update({ attachToExisting: " " }); // triggers fallback
                          } else {
                            update({ attachToExisting: e.target.value });
                          }
                        }}
                        className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 focus:outline-none focus:border-indigo-500 transition-colors"
                      >
                        <option value="" disabled>Select an existing project or job...</option>
                        {existingEntities.map((ent, idx) => (
                          <option key={idx} value={ent}>{ent}</option>
                        ))}
                        <option value="Other...">Other...</option>
                      </select>
                      {(!existingEntities.includes(answer.attachToExisting || "") && answer.attachToExisting) && (
                        <input
                          type="text"
                          value={answer.attachToExisting === " " ? "" : answer.attachToExisting}
                          onChange={(e) => update({ attachToExisting: e.target.value })}
                          placeholder="Type the name..."
                          className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors mt-2"
                        />
                      )}
                    </div>
                  ) : (
                    <input
                      type="text"
                      value={answer.attachToExisting || ""}
                      onChange={(e) => update({ attachToExisting: e.target.value })}
                      placeholder="e.g. My E-Commerce project, or TechCorp internship…"
                      className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors"
                    />
                  )}
                </div>
                <div>
                  <p className="text-xs text-zinc-400 mb-1">What did you implement / add? <span className="text-zinc-600">(optional)</span></p>
                  <textarea
                    value={answer.projectDescription || ""}
                    onChange={(e) => update({ projectDescription: e.target.value })}
                    placeholder="Describe what you built or added to this existing project."
                    rows={2}
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors"
                  />
                </div>
              </div>
            )}

            {answer.placementMode === 'project_or_exp' && answer.projectType === 'new' && (
              <div className="space-y-3 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                <div>
                  <p className="text-xs text-zinc-400 mb-1">Project Name</p>
                  <input
                    type="text"
                    value={answer.projectName || ""}
                    onChange={(e) => update({ projectName: e.target.value })}
                    placeholder="e.g. Real-time Chat App"
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors"
                  />
                </div>
                <div>
                  <p className="text-xs text-zinc-400 mb-1">GitHub / URL <span className="text-zinc-600">(optional)</span></p>
                  <input
                    type="text"
                    value={answer.projectUrl || ""}
                    onChange={(e) => update({ projectUrl: e.target.value })}
                    placeholder="https://github.com/..."
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors"
                  />
                </div>

                <div>
                  <p className="text-xs text-zinc-400 mb-1">Description</p>
                  <textarea
                    value={answer.projectDescription || ""}
                    onChange={(e) => update({ projectDescription: e.target.value })}
                    placeholder="Describe the project..."
                    rows={3}
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors"
                  />
                </div>
              </div>
            )}

          </div>
        )}


        {/* AI Follow-up clarification */}
        {answer.pendingQuestion && (
          <div className="bg-indigo-500/5 border border-indigo-500/20 rounded-xl p-4 space-y-3">
            <p className="text-xs font-semibold text-indigo-400 uppercase tracking-wider">AI Follow-up</p>
            <p className="text-sm text-zinc-200">{answer.pendingQuestion}</p>
            {answer.pendingOptions && answer.pendingOptions.length > 0 ? (
              <div className="space-y-2">
                {answer.pendingOptions.map((opt, oi) => (
                  <label key={oi} className="flex items-center gap-2 cursor-pointer">
                    <input type="radio" name={`clarify-${index}`} className="accent-indigo-500"
                      checked={answer.clarificationAnswer === opt}
                      onChange={() => update({ clarificationAnswer: opt })} />
                    <span className="text-sm text-zinc-300">{opt}</span>
                  </label>
                ))}
              </div>
            ) : (
              <input
                type="text"
                value={answer.clarificationAnswer || ""}
                onChange={(e) => update({ clarificationAnswer: e.target.value })}
                placeholder="Your answer..."
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors"
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ── WorkExperienceSection (standalone top-level section) ──────────────────────

export const EMPTY_EXPERIENCE: ExperienceEntry = { company: "", jobTitle: "", startDate: "", endDate: "", description: "" };

export interface ProjectEntry {
  name: string;
  tech: string;
  description: string;
  url: string;
  generateWithAI?: boolean;
}

const EMPTY_PROJECT: ProjectEntry = { name: "", tech: "", description: "", url: "", generateWithAI: false };

function WorkExperienceSection({
  entries,
  onChange,
}: {
  entries: ExperienceEntry[];
  onChange: (entries: ExperienceEntry[]) => void;
}) {
  const updateEntry = (i: number, field: keyof ExperienceEntry, value: string) => {
    onChange(entries.map((e, idx) => idx === i ? { ...e, [field]: value } : e));
  };
  const addEntry = () => onChange([...entries, { ...EMPTY_EXPERIENCE }]);
  const removeEntry = (i: number) => onChange(entries.filter((_, idx) => idx !== i));

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div>
          <h2 className="text-zinc-100 font-semibold text-base">Work Experience to Add</h2>
          <p className="text-zinc-500 text-xs mt-0.5">Add any work experience relevant to this JD. The AI will place it in your Professional Experience section.</p>
        </div>
        <button onClick={addEntry} className="flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 border border-indigo-500/30 hover:border-indigo-500/60 rounded-lg px-3 py-1.5 transition-colors shrink-0">
          <Plus size={12} /> Add Experience
        </button>
      </div>
      {entries.length === 0 ? (
        <button onClick={addEntry} className="w-full flex items-center justify-center gap-2 border border-dashed border-slate-700 rounded-xl py-5 text-zinc-600 hover:text-zinc-400 hover:border-slate-600 transition-colors text-sm">
          <Plus size={14} /> Click to add work experience
        </button>
      ) : (
        <div className="space-y-4">
          {entries.map((entry, i) => (
            <div key={i} className="bg-slate-800/50 border border-slate-700 rounded-xl p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-indigo-400 uppercase tracking-wider">Experience {entries.length > 1 ? i + 1 : ""}</span>
                <button onClick={() => removeEntry(i)} className="text-zinc-600 hover:text-red-400 transition-colors"><Trash2 size={13} /></button>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">Company Name</label>
                  <input type="text" value={entry.company} onChange={(e) => updateEntry(i, "company", e.target.value)}
                    placeholder="e.g. Google, Startup XYZ"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">Job Title / Role</label>
                  <input type="text" value={entry.jobTitle} onChange={(e) => updateEntry(i, "jobTitle", e.target.value)}
                    placeholder="e.g. Data Analyst Intern"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">Start Date</label>
                  <input type="text" value={entry.startDate} onChange={(e) => updateEntry(i, "startDate", e.target.value)}
                    placeholder="e.g. Jan 2023"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">End Date</label>
                  <input type="text" value={entry.endDate} onChange={(e) => updateEntry(i, "endDate", e.target.value)}
                    placeholder="e.g. Jun 2024 or Present"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1 block">Key responsibilities / technologies relevant to this JD</label>
                <textarea value={entry.description} onChange={(e) => updateEntry(i, "description", e.target.value)}
                  placeholder="Describe what you did. The AI will refine this into ATS-optimised resume bullets using JD keywords..."
                  rows={3} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors" />
              </div>
            </div>
          ))}
          <button onClick={addEntry} className="flex items-center gap-2 text-xs text-indigo-400 hover:text-indigo-300 border border-dashed border-indigo-500/30 hover:border-indigo-500/60 rounded-lg px-4 py-2 w-full justify-center transition-colors">
            <Plus size={13} /> Add Another Role
          </button>
        </div>
      )}
    </div>
  );
}

function ProjectsSection({
  entries,
  onChange,
}: {
  entries: ProjectEntry[];
  onChange: (entries: ProjectEntry[]) => void;
}) {
  const updateEntry = (i: number, field: keyof ProjectEntry, value: string | boolean) => {
    onChange(entries.map((e, idx) => idx === i ? { ...e, [field]: value } : e));
  };
  const addEntry = () => onChange([...entries, { ...EMPTY_PROJECT }]);
  const removeEntry = (i: number) => onChange(entries.filter((_, idx) => idx !== i));

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div>
          <h2 className="text-zinc-100 font-semibold text-base">Projects to Add / Update</h2>
          <p className="text-zinc-500 text-xs mt-0.5">Add new projects or add bullets to existing projects. The AI places them in the Projects section.</p>
        </div>
        <button onClick={addEntry} className="flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 border border-indigo-500/30 hover:border-indigo-500/60 rounded-lg px-3 py-1.5 transition-colors shrink-0">
          <Plus size={12} /> Add Project
        </button>
      </div>
      {entries.length === 0 ? (
        <button onClick={addEntry} className="w-full flex items-center justify-center gap-2 border border-dashed border-slate-700 rounded-xl py-5 text-zinc-600 hover:text-zinc-400 hover:border-slate-600 transition-colors text-sm">
          <Plus size={14} /> Click to add a project
        </button>
      ) : (
        <div className="space-y-4">
          {entries.map((entry, i) => (
            <div key={i} className="bg-slate-800/50 border border-slate-700 rounded-xl p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-indigo-400 uppercase tracking-wider">Project {entries.length > 1 ? i + 1 : ""}</span>
                <button onClick={() => removeEntry(i)} className="text-zinc-600 hover:text-red-400 transition-colors"><Trash2 size={13} /></button>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">Project Name {entry.generateWithAI && <span className="text-zinc-600">(optional)</span>}</label>
                  <input type="text" value={entry.name} onChange={(e) => updateEntry(i, "name", e.target.value)}
                    placeholder={entry.generateWithAI ? "e.g. Simple Analytics Dashboard" : "e.g. Customer Churn Predictor"}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">Technologies Used {entry.generateWithAI && <span className="text-rose-400">*</span>}</label>
                  <input type="text" value={entry.tech} onChange={(e) => updateEntry(i, "tech", e.target.value)}
                    placeholder="e.g. Python, PostgreSQL, Docker"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
              </div>
              
              {!entry.generateWithAI && (
                <div>
                  <label className="text-xs text-zinc-500 mb-1 block">What you built / What it does</label>
                  <textarea value={entry.description} onChange={(e) => updateEntry(i, "description", e.target.value)}
                    placeholder="Describe what the project does and what you built..."
                    rows={3} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors" />
                </div>
              )}
              <div>
                <label className="text-xs text-zinc-500 mb-1 block">GitHub / Live URL <span className="text-zinc-700">(optional)</span></label>
                <input type="text" value={entry.url} onChange={(e) => updateEntry(i, "url", e.target.value)}
                  placeholder="https://github.com/..."
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-indigo-500 transition-colors" />
              </div>
            </div>
          ))}
          <button onClick={addEntry} className="flex items-center gap-2 text-xs text-indigo-400 hover:text-indigo-300 border border-dashed border-indigo-500/30 hover:border-indigo-500/60 rounded-lg px-4 py-2 w-full justify-center transition-colors">
            <Plus size={13} /> Add Another Project
          </button>
        </div>
      )}
    </div>
  );
}



// ── ImprovementsList ──────────────────────────────────────────────────────────

function OptimizationsList({
  optimizeProjects,
  setOptimizeProjects,
  optimizeExperience,
  setOptimizeExperience,
  optimizeSummary,
  setOptimizeSummary,
}: {
  optimizeProjects: boolean;
  setOptimizeProjects: (v: boolean) => void;
  optimizeExperience: boolean;
  setOptimizeExperience: (v: boolean) => void;
  optimizeSummary: boolean;
  setOptimizeSummary: (v: boolean) => void;
}) {
  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div>
          <h2 className="text-zinc-100 font-semibold text-base">Terminology Improvements</h2>
          <p className="text-zinc-500 text-xs mt-0.5">
            Allow our AI to rewrite sections of your resume to naturally incorporate JD keywords.
          </p>
        </div>
      </div>
      <div className="space-y-3">
        <label className={`group flex items-center gap-4 rounded-2xl p-4 cursor-pointer border transition-all duration-300 ease-out ${optimizeProjects ? "bg-indigo-500/10 border-indigo-500/50 shadow-[0_0_15px_rgba(99,102,241,0.1)]" : "bg-slate-800/40 border-slate-700/60 hover:bg-slate-800/80 hover:border-indigo-500/30"}`}>
          <div className="relative flex items-center justify-center shrink-0 w-6 h-6">
            <input type="checkbox" checked={optimizeProjects} onChange={(e) => setOptimizeProjects(e.target.checked)} className="peer sr-only" />
            <div className={`w-full h-full rounded-md border-2 flex items-center justify-center transition-all duration-300 ${optimizeProjects ? "bg-indigo-500 border-indigo-500" : "border-slate-600 group-hover:border-indigo-400/50"}`}>
              <svg className={`w-3.5 h-3.5 text-white transition-transform duration-300 ${optimizeProjects ? "scale-100" : "scale-0"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
            </div>
          </div>
          <div className="flex-1 min-w-0">
            <span className={`text-sm leading-relaxed block transition-colors ${optimizeProjects ? "text-indigo-100" : "text-zinc-300"}`}>Optimize wording in your <b>Projects</b> section</span>
          </div>
        </label>
        <label className={`group flex items-center gap-4 rounded-2xl p-4 cursor-pointer border transition-all duration-300 ease-out ${optimizeExperience ? "bg-indigo-500/10 border-indigo-500/50 shadow-[0_0_15px_rgba(99,102,241,0.1)]" : "bg-slate-800/40 border-slate-700/60 hover:bg-slate-800/80 hover:border-indigo-500/30"}`}>
          <div className="relative flex items-center justify-center shrink-0 w-6 h-6">
            <input type="checkbox" checked={optimizeExperience} onChange={(e) => setOptimizeExperience(e.target.checked)} className="peer sr-only" />
            <div className={`w-full h-full rounded-md border-2 flex items-center justify-center transition-all duration-300 ${optimizeExperience ? "bg-indigo-500 border-indigo-500" : "border-slate-600 group-hover:border-indigo-400/50"}`}>
              <svg className={`w-3.5 h-3.5 text-white transition-transform duration-300 ${optimizeExperience ? "scale-100" : "scale-0"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
            </div>
          </div>
          <div className="flex-1 min-w-0">
            <span className={`text-sm leading-relaxed block transition-colors ${optimizeExperience ? "text-indigo-100" : "text-zinc-300"}`}>Optimize wording in your <b>Experience</b> section</span>
          </div>
        </label>
        <label className={`group flex items-center gap-4 rounded-2xl p-4 cursor-pointer border transition-all duration-300 ease-out ${optimizeSummary ? "bg-indigo-500/10 border-indigo-500/50 shadow-[0_0_15px_rgba(99,102,241,0.1)]" : "bg-slate-800/40 border-slate-700/60 hover:bg-slate-800/80 hover:border-indigo-500/30"}`}>
          <div className="relative flex items-center justify-center shrink-0 w-6 h-6">
            <input type="checkbox" checked={optimizeSummary} onChange={(e) => setOptimizeSummary(e.target.checked)} className="peer sr-only" />
            <div className={`w-full h-full rounded-md border-2 flex items-center justify-center transition-all duration-300 ${optimizeSummary ? "bg-indigo-500 border-indigo-500" : "border-slate-600 group-hover:border-indigo-400/50"}`}>
              <svg className={`w-3.5 h-3.5 text-white transition-transform duration-300 ${optimizeSummary ? "scale-100" : "scale-0"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
            </div>
          </div>
          <div className="flex-1 min-w-0">
            <span className={`text-sm leading-relaxed block transition-colors ${optimizeSummary ? "text-indigo-100" : "text-zinc-300"}`}>Optimize wording in your <b>Professional Summary</b></span>
          </div>
        </label>
      </div>
    </div>
  );
}

function ImprovementsList({
  improvements,
  selectedImprovements,
  onToggle,
}: {
  improvements: string[];
  selectedImprovements: Set<number>;
  onToggle: (index: number) => void;
}) {
  if (!improvements || improvements.length === 0) return null;
  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div>
          <h2 className="text-zinc-100 font-semibold text-base">Specific Improvements</h2>
          <p className="text-zinc-500 text-xs mt-0.5">
            Select the specific wording improvements you'd like the AI to apply to your resume.
          </p>
        </div>
      </div>
      <div className="space-y-3">
        {improvements.map((improvement, i) => {
          const isSelected = selectedImprovements.has(i);
          return (
            <label key={i} className={`group flex items-start gap-4 rounded-2xl p-4 cursor-pointer border transition-all duration-300 ease-out ${isSelected ? "bg-indigo-500/10 border-indigo-500/50 shadow-[0_0_15px_rgba(99,102,241,0.1)]" : "bg-slate-800/40 border-slate-700/60 hover:bg-slate-800/80 hover:border-indigo-500/30"}`}>
              <div className="relative flex items-center justify-center shrink-0 w-6 h-6 mt-0.5">
                <input type="checkbox" checked={isSelected} onChange={() => onToggle(i)} className="peer sr-only" />
                <div className={`w-full h-full rounded-md border-2 flex items-center justify-center transition-all duration-300 ${isSelected ? "bg-indigo-500 border-indigo-500" : "border-slate-600 group-hover:border-indigo-400/50"}`}>
                  <svg className={`w-3.5 h-3.5 text-white transition-transform duration-300 ${isSelected ? "scale-100" : "scale-0"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                </div>
              </div>
              <div className="flex-1 min-w-0">
                <span className={`text-sm leading-relaxed block transition-colors ${isSelected ? "text-indigo-100" : "text-zinc-300"}`}>{improvement}</span>
              </div>
            </label>
          );
        })}
      </div>
    </div>
  );
}

// ── CustomAdditionsField ──────────────────────────────────────────────────────

function CustomAdditionsField({
  value,
  onChange,
}: {
  value: string;
  onChange: (v: string) => void;
}) {
  return (
    <div>
      <h2 className="text-zinc-100 font-semibold text-base mb-1">Custom Additions</h2>
      <p className="text-zinc-500 text-xs mb-3">
        Add any extra content you want included in your resume.
      </p>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Add certifications, education, or other content..."
        rows={5}
        className="w-full bg-slate-800/50 border border-slate-700 rounded-xl px-4 py-3 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors"
      />
      <p className="text-zinc-600 text-xs mt-2 leading-relaxed">
        Tip: prefix lines with <code className="text-indigo-400">certificate:</code>, <code className="text-indigo-400">education:</code>, or{" "}
        <code className="text-indigo-400">achievement:</code> to place them in the correct resume
        section (e.g., <code className="text-zinc-500">achievement: Published a review paper on fire detection</code>).
      </p>
    </div>
  );
}

// ── TemplatePicker ────────────────────────────────────────────────────────────

const TEMPLATES = ["Classic ATS with black", "Classic ATS with blue", "Two Column with black", "Two Column with blue"] as const;
type Template = (typeof TEMPLATES)[number];

function TemplatePicker({
  selected,
  onSelect,
}: {
  selected: Template;
  onSelect: (t: Template) => void;
}) {
  return (
    <div>
      <h2 className="text-zinc-100 font-semibold text-base mb-1">PDF Template</h2>
      <p className="text-zinc-500 text-xs mb-3">Choose the visual style for your resume.</p>
      <div className="flex flex-wrap gap-2">
        {TEMPLATES.map((t) => (
          <button
            key={t}
            onClick={() => onSelect(t)}
            className={`px-4 py-2 rounded-lg text-sm font-medium border transition-colors ${
              selected === t
                ? "bg-indigo-600 border-indigo-500 text-white"
                : "bg-slate-800 border-slate-700 text-zinc-400 hover:border-slate-500 hover:text-zinc-200"
            }`}
          >
            {t}
          </button>
        ))}
      </div>
    </div>
  );
}

// ── RefinedItemCard ───────────────────────────────────────────────────────────
// approved: null = default (treated as approved), true = explicitly approved, false = rejected

function RefinedItemCard({
  label,
  content,
  approved,
  onApprove,
  onReject,
}: {
  label: string;
  content: string;
  approved: boolean | null;
  onApprove: () => void;
  onReject: () => void;
}) {
  const isRejected = approved === false;
  const isApproved = approved === true || approved === null;

  return (
    <div
      className={`bg-slate-800/50 border rounded-xl p-5 transition-all ${
        isRejected
          ? "border-red-500/30 opacity-50"
          : "border-slate-700"
      }`}
    >
      <div className="flex items-start justify-between gap-3 mb-3">
        <p className="text-zinc-400 text-xs font-medium uppercase tracking-wide">{label}</p>
        {isRejected ? (
          <span className="text-xs font-semibold text-red-400 bg-red-500/10 border border-red-500/20 rounded-full px-2 py-0.5 shrink-0">
            Rejected
          </span>
        ) : (
          <span className="text-xs font-semibold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 rounded-full px-2 py-0.5 shrink-0">
            Approved
          </span>
        )}
      </div>
      <div className="text-zinc-200 text-sm leading-relaxed mb-4 space-y-1">
        {(() => {
          if (content.startsWith("experience_bullet:")) {
            const parts = content.replace("experience_bullet:", "").split("|").map(s => s.trim());
            if (parts.length >= 4) {
              return (
                <>
                  <p className="font-semibold text-indigo-300">{parts[1]} - {parts[0]}</p>
                  <p className="text-xs text-zinc-400 mb-2">{parts[2]}</p>
                  <ul className="list-disc pl-5 space-y-1">
                    {parts.slice(3).join(" | ").split("---").map((b, i) => (
                      <li key={i}>{b.trim()}</li>
                    ))}
                  </ul>
                </>
              );
            }
          } else if (content.startsWith("project:")) {
            const parts = content.replace("project:", "").split("—").map(s => s.trim());
            
            // If there's no "—", the AI might have just used "---" for everything
            const titlePart = parts[0];
            const bulletParts = parts.length > 1 ? parts.slice(1).join(" — ").split("---") : titlePart.split("---").slice(1);
            const actualTitle = parts.length > 1 ? titlePart : titlePart.split("---")[0];

            return (
              <>
                <p className="font-semibold text-indigo-300">{actualTitle}</p>
                <ul className="list-disc pl-5 space-y-1 mt-2">
                  {bulletParts.map((b, i) => (
                    <li key={i}>{b.trim()}</li>
                  ))}
                </ul>
              </>
            );
          } else if (content.startsWith("add_to_project:")) {
            const parts = content.replace("add_to_project:", "").split("|").map(s => s.trim());
            if (parts.length >= 2) {
              return (
                <>
                  <p className="font-semibold text-indigo-300">Added to Project: {parts[0]}</p>
                  <ul className="list-disc pl-5 space-y-1 mt-2">
                    {parts.slice(1).join(" | ").split("---").map((b, i) => (
                      <li key={i}>{b.trim()}</li>
                    ))}
                  </ul>
                </>
              );
            }
          }
          return <p>{content}</p>;
        })()}
      </div>
      <div className="flex gap-2">
        <button
          onClick={onApprove}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
            isApproved
              ? "bg-emerald-600 border-emerald-500 text-white"
              : "bg-slate-700 border-slate-600 text-zinc-400 hover:border-emerald-500/50 hover:text-emerald-400"
          }`}
        >
          Approve
        </button>
        <button
          onClick={onReject}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
            isRejected
              ? "bg-red-600 border-red-500 text-white"
              : "bg-slate-700 border-slate-600 text-zinc-400 hover:border-red-500/50 hover:text-red-400"
          }`}
        >
          Reject
        </button>
      </div>
    </div>
  );
}

function WizardStepper({ currentStep, onStepClick }: { currentStep: number, onStepClick?: (step: number) => void }) {
  const steps = [
    { num: 1, label: "Add Context" },
    { num: 2, label: "Address Gaps" },
    { num: 3, label: "Review & Generate" }
  ];

  return (
    <div className="flex items-center justify-center w-full mb-8 relative px-4">
      <div className="absolute left-8 right-8 top-1/2 h-px bg-slate-800 -z-10 transform -translate-y-1/2 max-w-lg mx-auto" />
      <div className="flex justify-between w-full max-w-lg mx-auto relative z-10">
        {steps.map((step) => {
          const isCurrent = currentStep === step.num;
          const isPast = currentStep > step.num;
          return (
            <button
              key={step.num}
              onClick={() => {
                if (isPast && onStepClick) onStepClick(step.num);
              }}
              disabled={!isPast && !isCurrent}
              className={`flex flex-col items-center gap-2.5 bg-slate-950 px-2 outline-none ${isPast ? "cursor-pointer hover:opacity-80" : "cursor-default"}`}
            >
              <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold border-2 transition-all duration-300 ${
                isCurrent ? "bg-indigo-600 border-indigo-500 text-white shadow-[0_0_15px_rgba(99,102,241,0.4)] scale-110" :
                isPast ? "bg-emerald-500/10 border-emerald-500/50 text-emerald-400" :
                "bg-slate-900 border-slate-800 text-slate-500"
              }`}>
                {isPast ? <TrendingUp size={14} className="text-emerald-400" /> : step.num}
              </div>
              <span className={`text-[11px] uppercase tracking-wider font-semibold transition-colors ${
                isCurrent ? "text-indigo-300" :
                isPast ? "text-emerald-500/70" :
                "text-slate-600"
              }`}>
                {step.label}
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function ResumeUpgradeWizardPage({
  params,
}: {
  params: Promise<{ session_id: string }>;
}) {
  const { session_id } = use(params);
  const router = useRouter();

  const [session, setSession] = useState<SessionDetail | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);

  
  // Step 1 state — structured gap answers (skill knowledge only)
  const [gapAnswers, setGapAnswers] = useState<Record<number, GapAnswer>>({});
  // Standalone top-level experience and project entries
  const [standaloneExperiences, setStandaloneExperiences] = useState<ExperienceEntry[]>([]);
  const [standaloneProjects, setStandaloneProjects] = useState<ProjectEntry[]>([]);
  const [selectedImprovements, setSelectedImprovements] = useState<Set<number>>(new Set());
  const [optimizeProjects, setOptimizeProjects] = useState(false);
  const [optimizeExperience, setOptimizeExperience] = useState(false);
  const [optimizeSummary, setOptimizeSummary] = useState(false);
  const [customAdditions, setCustomAdditions] = useState("");
  const [targetedAnswers, setTargetedAnswers] = useState<Record<string, string>>({});

  const [selectedTemplate, setSelectedTemplate] = useState<Template>("Classic ATS with black");
  
  // Wizard state
  const [wizardStep, setWizardStep] = useState<1 | 2 | 3>(1);
  const [isReanalyzing, setIsReanalyzing] = useState(false);
  const [remainingGaps, setRemainingGaps] = useState<Set<string> | null>(null);

  // Caching refs for Step 1 -> Step 2 transition
  const lastReanalyzedCustom = useRef<string | null>(null);
  const lastReanalyzeResult = useRef<Set<string> | null>(null);

  // Caching refs for Step 2 -> Step 3 transition
  const lastRefinedInputs = useRef<{
    combinedCustom: string;
    gapSelections: Record<string, string>;
    selectedImprovementStrings: string[];
    optimizeProjects: boolean;
    optimizeExperience: boolean;
    optimizeSummary: boolean;
    targetedAnswers: Record<string, string>;
  } | null>(null);

  const lastRefineResult = useRef<{
    refinedGaps: Record<string, string>;
    refinedCustomItems: string[];
  } | null>(null);

  // Step 2 & 3 state
  const [isRefining, setIsRefining] = useState(false);
  const [refineError, setRefineError] = useState<string | null>(null);
  const [refinedGaps, setRefinedGaps] = useState<Record<string, string>>({});
  const [refinedCustomItems, setRefinedCustomItems] = useState<string[]>([]);
  // null = default (approved), true = explicitly approved, false = rejected
  const [approvedGaps, setApprovedGaps] = useState<Record<string, boolean | null>>({});
  const [approvedCustomItems, setApprovedCustomItems] = useState<Record<number, boolean | null>>({});
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);

  // Fetch session on mount
  useEffect(() => {
    fetchSession(session_id)
      .then((data) => {
        setSession(data);
        // Initialize gap answers (skill mode only) for both normal gaps and targeted questions
        const gaps = data.enhanced_analysis?.gaps ?? [];
        const qs = data.enhanced_analysis?.targeted_questions ?? [];
        const initial: Record<number, GapAnswer> = {};
        for (let i = 0; i < gaps.length + qs.length; i++) {
          initial[i] = { mode: "skill", hasExperience: false };
        }
        setGapAnswers(initial);
        setSelectedImprovements(new Set());
      })
      .catch((err) => {
        setLoadError(err instanceof ApiError ? err.detail : "Failed to load session.");
      });
  }, [session_id]);

  const handleGapAnswerChange = (index: number, answer: GapAnswer) => {
    setGapAnswers((prev) => ({ ...prev, [index]: answer }));
  };

  const handleToggleImprovement = (index: number) => {
    setSelectedImprovements((prev) => {
      const next = new Set(prev);
      if (next.has(index)) {
        next.delete(index);
      } else {
        next.add(index);
      }
      return next;
    });
  };

  // Step 1 → Step 2: reanalyze gaps if projects/experiences added
  const handleNextToPart2 = async () => {
    const extraLines: string[] = [];
    standaloneExperiences.forEach((e) => {
      const s = serializeExperienceEntry(e);
      if (s) extraLines.push(s);
    });
    standaloneProjects.forEach((p) => {
      const s = serializeProjectEntry(p);
      if (s) extraLines.push(s);
    });
    const combinedCustom = extraLines.join("\n").trim();

    if (!combinedCustom) {
      setWizardStep(2);
      return;
    }

    // Bypass API call if input has not changed since last reanalysis
    if (lastReanalyzedCustom.current === combinedCustom && lastReanalyzeResult.current !== null) {
      setRemainingGaps(lastReanalyzeResult.current);
      setWizardStep(2);
      return;
    }

    setIsReanalyzing(true);
    setRefineError(null);
    try {
      const result = await reanalyzeGaps(session_id, combinedCustom);
      const newRemainingGaps = new Set(result.remaining_gaps);

      // Add unanswered targeted questions to remaining gaps
      const tq = session?.enhanced_analysis?.targeted_questions ?? [];
      tq.forEach(q => {
        if (!targetedAnswers[q] || targetedAnswers[q].trim().length < 5) {
          newRemainingGaps.add(q);
        }
      });

      lastReanalyzedCustom.current = combinedCustom;
      lastReanalyzeResult.current = newRemainingGaps;
      setRemainingGaps(newRemainingGaps);
      setWizardStep(2);
    } catch (err) {
      setRefineError(err instanceof ApiError ? err.detail : "Failed to analyze additions.");
    } finally {
      setIsReanalyzing(false);
    }
  };

  // Step 2 → Step 3: serialize everything and call /refine
  const handleRefine = async (overrideGapsSet?: Set<string>, overrideExtraLines?: string) => {
    if (!session) return;
    setIsRefining(true);
    setRefineError(null);

    try {
      const gaps = [
        ...(session.enhanced_analysis?.gaps ?? []),
        ...(session.enhanced_analysis?.targeted_questions ?? [])
      ];
      const activeSet = overrideGapsSet ?? remainingGaps;
      const activeGapsIndices = gaps
        .map((gap: string, i: number) => (activeSet === null || activeSet.has(gap) ? i : -1))
        .filter((i: number) => i !== -1);

      const improvements = session.enhanced_analysis?.improvements ?? [];
      const selectedImprovementStrings = improvements.filter((_, i) =>
        selectedImprovements.has(i)
      );

      // Serialize skill-only gap answers for active gaps ONLY
      const gapSelections: Record<string, string> = {};

      activeGapsIndices.forEach((i: number) => {
        const answer = gapAnswers[i];
        if (!answer) return;

        const serialized = serializeGapAnswer(gaps[i], answer);
        if (serialized.trim()) gapSelections[String(i)] = serialized.trim();
      });

      // Serialize standalone experience and project entries as extra custom additions
      let finalCustomLines = overrideExtraLines;
      if (finalCustomLines === undefined) {
        const extraLines: string[] = [];
        standaloneExperiences.forEach((e) => {
          const s = serializeExperienceEntry(e);
          if (s) extraLines.push(s);
        });
        standaloneProjects.forEach((p) => {
          const s = serializeProjectEntry(p);
          if (s) extraLines.push(s);
        });
        finalCustomLines = extraLines.join("\n");
      }

      const combinedCustom = [customAdditions, finalCustomLines].filter(Boolean).join("\n");

      // Build object containing current inputs to check for changes
      const currentInputs = {
        combinedCustom,
        gapSelections,
        selectedImprovementStrings,
        optimizeProjects,
        optimizeExperience,
        optimizeSummary,
        targetedAnswers
      };

      const hasChanged =
        !lastRefinedInputs.current ||
        lastRefinedInputs.current.combinedCustom !== currentInputs.combinedCustom ||
        lastRefinedInputs.current.optimizeProjects !== currentInputs.optimizeProjects ||
        lastRefinedInputs.current.optimizeExperience !== currentInputs.optimizeExperience ||
        lastRefinedInputs.current.optimizeSummary !== currentInputs.optimizeSummary ||
        JSON.stringify(lastRefinedInputs.current.gapSelections) !== JSON.stringify(currentInputs.gapSelections) ||
        JSON.stringify(lastRefinedInputs.current.selectedImprovementStrings) !== JSON.stringify(currentInputs.selectedImprovementStrings) ||
        JSON.stringify(lastRefinedInputs.current.targetedAnswers) !== JSON.stringify(currentInputs.targetedAnswers);

      if (!hasChanged && lastRefineResult.current) {
        // No changes detected! Transition directly to Step 3 using cached refined outputs
        setRefinedGaps(lastRefineResult.current.refinedGaps);
        setRefinedCustomItems(lastRefineResult.current.refinedCustomItems);
        // Retain existing user decisions, initializing missing ones if empty
        if (Object.keys(approvedGaps).length === 0) {
          setApprovedGaps(Object.fromEntries(Object.keys(lastRefineResult.current.refinedGaps).map((k) => [k, null])));
        }
        if (Object.keys(approvedCustomItems).length === 0) {
          setApprovedCustomItems(Object.fromEntries(lastRefineResult.current.refinedCustomItems.map((_, i) => [i, null])));
        }
        setWizardStep(3);
        setIsRefining(false);
        return;
      }

      if (Object.keys(gapSelections).length === 0 && combinedCustom.trim() === "" && selectedImprovementStrings.length === 0 && !optimizeProjects && !optimizeExperience && !optimizeSummary && Object.keys(targetedAnswers).length === 0) {
        // Nothing to refine! Just skip to step 3 so they can pick a template and download
        // Invalidate cache since there is no actual content
        lastRefinedInputs.current = null;
        lastRefineResult.current = null;
        setRefinedGaps({});
        setRefinedCustomItems([]);
        setApprovedGaps({});
        setApprovedCustomItems({});
        setWizardStep(3);
        setIsRefining(false);
        return;
      }

      const result = await refineWithGaps(
        session_id,
        combinedCustom,
        gapSelections,
        selectedImprovementStrings,
        false,
        {
          projects: optimizeProjects,
          experience: optimizeExperience,
          summary: optimizeSummary
        },
        targetedAnswers
      );

      const refinedGapsResult = result.refined_gaps ?? {};
      const customItems = result.refined_custom_items ?? [];

      // Save inputs and results to cache
      lastRefinedInputs.current = currentInputs;
      lastRefineResult.current = {
        refinedGaps: refinedGapsResult,
        refinedCustomItems: customItems
      };

      setRefinedGaps(refinedGapsResult);
      setRefinedCustomItems(customItems);
      setApprovedGaps(Object.fromEntries(Object.keys(refinedGapsResult).map((k) => [k, null])));
      setApprovedCustomItems(Object.fromEntries(customItems.map((_, i) => [i, null])));
      setWizardStep(3);
    } catch (err) {
      setRefineError((err as any)?.detail || (err as Error)?.message || "Failed to refine resume.");
    } finally {
      setIsRefining(false);
    }
  };

  // Step 2: persist only approved items via /refine (pre_refined=true), then generate PDF
  const handleGenerate = async () => {
    if (!session) return;
    setIsGenerating(true);
    setGenerateError(null);

    try {
      // Collect approved gap paragraphs (null = default approved, true = explicitly approved)
      const approvedGapSelections: Record<string, string> = {};
      Object.entries(refinedGaps).forEach(([key, content]) => {
        if (approvedGaps[key] !== false) {
          approvedGapSelections[key] = content;
        }
      });

      // Collect approved custom items
      const approvedCustomLines = refinedCustomItems.filter(
        (_, i) => approvedCustomItems[i] !== false
      );

      // Persist only approved content via /refine with pre_refined=true (skips LLM)
      await refineWithGaps(
        session_id,
        approvedCustomLines.join("\n"),
        approvedGapSelections,
        [],
        true
      );

      // Generate and download the PDF
      const blob = await generatePDF(session_id, selectedTemplate);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `improved-resume-${session_id}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      setGenerateError(
        err instanceof ApiError ? err.detail : "Failed to generate resume. Please try again."
      );
    } finally {
      setIsGenerating(false);
    }
  };

  // ── Loading state ──────────────────────────────────────────────────────────
  if (!session && !loadError) {
    return (
      <main className="flex flex-col items-center justify-center min-h-screen bg-slate-900 gap-6">
        <div className="relative flex items-center justify-center">
          <span className="absolute inline-flex h-16 w-16 rounded-full bg-indigo-500/30 animate-ping" />
          <span className="relative inline-flex h-10 w-10 rounded-full bg-indigo-500" />
        </div>
        <p className="text-zinc-400 text-sm">Loading session...</p>
      </main>
    );
  }

  // ── Error state ────────────────────────────────────────────────────────────
  if (loadError) {
    return (
      <main className="flex flex-col items-center justify-center min-h-screen bg-slate-900 gap-4">
        <p className="text-red-400 text-sm">{loadError}</p>
        <Link
          href={`/practice/${session_id}`}
          className="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium rounded-lg transition-colors"
        >
          Back to Report
        </Link>
      </main>
    );
  }

  const allGaps = [
    ...(session?.enhanced_analysis?.gaps ?? []),
    ...(session?.enhanced_analysis?.targeted_questions ?? [])
  ];
  const activeGapsIndices = allGaps
    .map((gap: string, i: number) => (remainingGaps === null || remainingGaps.has(gap) ? i : -1))
    .filter((i: number) => i !== -1);

  if (wizardStep === 1 || wizardStep === 2) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-200 selection:bg-indigo-500/30 flex flex-col items-center py-12 px-6">
        <div className="w-full max-w-4xl space-y-6">
          <Link href={`/practice/${session_id}`} className="text-zinc-500 hover:text-indigo-400 text-sm font-medium transition-colors mb-6 inline-block">
            ← Back to Dashboard
          </Link>

          <WizardStepper currentStep={wizardStep} onStepClick={(step) => setWizardStep(step as 1|2|3)} />
          
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl relative overflow-hidden">
            {session && (
              <div className="mb-8">
                <ScoreComparisonBanner 
                  session={session} 
                  selectedImprovementsCount={selectedImprovements.size}
                  totalGapsCount={allGaps.length}
                  addressedGapsCount={
                    wizardStep === 1 
                      ? standaloneExperiences.filter(e => e.company.trim() || e.description.trim()).length + 
                        standaloneProjects.filter(p => p.name.trim() || p.description.trim() || p.tech.trim()).length 
                      : (allGaps.length - activeGapsIndices.length) + Object.values(gapAnswers).filter((ans) => {
                          if (!ans) return false;
                          if (ans.generateProject) return true;
                          if (ans.hasExperience === 'ai_generate') return true;
                          if (ans.hasExperience === true) {
                            const text = ans.skillNote || ans.projectDescription;
                            return text && text.trim().length > 0;
                          }
                          return false;
                        }).length
                  }
                />
              </div>
            )}
            
            <h1 className="text-3xl font-bold text-white mb-2 max-w-lg">Let's Upgrade Your Resume</h1>
            <p className="text-slate-400 mb-8 max-w-xl">
              {wizardStep === 1 
                ? "First, let's add any missing work experiences or projects. We'll use these to cover as many required skills as possible." 
                : "Now, let's address the remaining skill gaps that weren't covered by your new experiences and projects."}
            </p>

            {wizardStep === 1 && (
              <div className="space-y-12">
                <WorkExperienceSection entries={standaloneExperiences} onChange={setStandaloneExperiences} />
                <ProjectsSection entries={standaloneProjects} onChange={setStandaloneProjects} />

                {session?.enhanced_analysis?.targeted_questions && session.enhanced_analysis.targeted_questions.length > 0 && (
                  <div className="space-y-4">
                    <div className="flex items-center gap-2">
                      <div className="bg-indigo-500/20 p-1.5 rounded text-indigo-400">
                        <MessageCircle size={18} />
                      </div>
                      <h2 className="text-xl font-semibold text-zinc-100">Targeted Questions</h2>
                    </div>
                    <p className="text-zinc-400 text-sm">We noticed some missing details in your resume that are important for this role. Answering these questions will help the AI rewrite your experiences perfectly.</p>
                    <div className="space-y-4 bg-slate-900/50 p-6 rounded-xl border border-slate-700/50">
                      {session.enhanced_analysis.targeted_questions.map((q, idx) => (
                        <div key={idx} className="space-y-2">
                          <p className="text-zinc-200 text-sm font-medium">{q}</p>
                          <textarea
                            value={targetedAnswers[q] || ""}
                            onChange={(e) => setTargetedAnswers(prev => ({ ...prev, [q]: e.target.value }))}
                            placeholder="Your answer... (Leave blank if not applicable)"
                            rows={2}
                            className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors"
                          />
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <ImprovementsList
                  improvements={session?.enhanced_analysis?.improvements ?? []}
                  selectedImprovements={selectedImprovements}
                  onToggle={handleToggleImprovement}
                />
                
                <OptimizationsList 
                  optimizeProjects={optimizeProjects} setOptimizeProjects={setOptimizeProjects}
                  optimizeExperience={optimizeExperience} setOptimizeExperience={setOptimizeExperience}
                  optimizeSummary={optimizeSummary} setOptimizeSummary={setOptimizeSummary}
                />
                <button
                  onClick={handleNextToPart2}
                  disabled={isReanalyzing}
                  className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-semibold shadow-lg shadow-indigo-900/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isReanalyzing ? "Analyzing Additions..." : "Next: Address Remaining Skills →"}
                </button>
              </div>
            )}

            {wizardStep === 2 && (
              <div className="space-y-12">
                {activeGapsIndices.length === 0 ? (
                  <div className="text-center py-12 bg-slate-800/30 border border-slate-700/50 rounded-2xl">
                    <p className="text-emerald-400 font-semibold mb-2">Great job!</p>
                    <p className="text-slate-400 text-sm">Your new experiences and projects have covered all the missing skills!</p>
                  </div>
                ) : (
                  <div className="space-y-6">
                    <div className="flex items-center justify-between">
                      <div>
                        <h2 className="text-zinc-100 font-semibold text-base">Remaining Skill Gaps</h2>
                        <p className="text-zinc-500 text-xs mt-0.5">Let's check if you have knowledge for these remaining skills.</p>
                      </div>
                    </div>
                    {activeGapsIndices.map((i: number) => {
                      const gap = allGaps[i];
                      return (
                        <SmartGapCard
                          key={i}
                          index={i}
                          gap={gap}
                          answer={gapAnswers[i]!}
                          onChange={handleGapAnswerChange}
                          existingEntities={session?.enhanced_analysis?.existing_entities || []}
                        />
                      );
                    })}
                  </div>
                )}

                <div className="mt-8 border-t border-slate-800 pt-8 space-y-8">
                  {/* Custom additions */}
                  <CustomAdditionsField value={customAdditions} onChange={setCustomAdditions} />
                </div>
                
                <div className="flex gap-4">
                  <button
                    onClick={() => setWizardStep(1)}
                    className="px-6 py-3.5 bg-slate-800 hover:bg-slate-700 text-white rounded-xl font-semibold shadow-lg transition-all"
                  >
                    ← Back
                  </button>
                  <button
                    onClick={() => handleRefine()}
                    disabled={isRefining}
                    className="flex-1 py-3.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-semibold shadow-lg shadow-indigo-900/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  >
                    {isRefining ? "Refining Resume..." : "Refine My Resume ✨"}
                  </button>
                </div>
              </div>
            )}
            {refineError && <p className="text-red-400 text-sm mt-4 text-center">{refineError}</p>}
          </div>
        </div>
      </div>
    );
  }

  // ── Step 3: Refinement Review ──────────────────────────────────────────────
  const gapEntries = Object.entries(refinedGaps);
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 selection:bg-indigo-500/30 flex flex-col items-center py-12 px-6">
      <div className="w-full max-w-4xl space-y-6">
        <div className="flex items-center justify-between mb-6">
          <Link href={`/practice/${session_id}`} className="text-zinc-500 hover:text-indigo-400 text-sm font-medium transition-colors inline-block">
            ← Back to Dashboard
          </Link>
          <button
            onClick={() => setWizardStep(2)}
            className="px-4 py-2 text-xs rounded-lg bg-slate-800 hover:bg-slate-700 text-zinc-400 border border-slate-700 transition-colors"
          >
            ← Revise Inputs
          </button>
        </div>

        <WizardStepper currentStep={3} />
        
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl relative overflow-hidden space-y-10">
          
          <div>
            <h1 className="text-3xl font-bold text-white mb-2 max-w-lg">Review & Generate</h1>
            <p className="text-slate-400 mb-8 max-w-xl">
              Review each AI-refined item. Approve or reject before generating the final PDF.
            </p>
          </div>

          <ScoreComparisonBanner 
            session={session!} 
            selectedImprovementsCount={selectedImprovements.size}
            totalGapsCount={allGaps.length}
            addressedGapsCount={Object.keys(refinedGaps).filter(key => approvedGaps[key] !== false).length}
          />

          {/* Refined gap paragraphs */}
          {gapEntries.length > 0 && (
            <div>
              <h2 className="text-zinc-100 font-semibold text-base mb-1">Refined Gap Responses</h2>
              <div className="space-y-4 mt-4">
                {gapEntries.map(([key, content]) => {
                  const gapIndex = parseInt(key, 10);
                  const label = allGaps[gapIndex] ?? `Gap ${gapIndex + 1}`;
                  return (
                    <RefinedItemCard
                      key={key}
                      label={label}
                      content={content}
                      approved={approvedGaps[key] ?? null}
                      onApprove={() =>
                        setApprovedGaps((prev) => ({ ...prev, [key]: true }))
                      }
                      onReject={() =>
                        setApprovedGaps((prev) => ({ ...prev, [key]: false }))
                      }
                    />
                  );
                })}
              </div>
            </div>
          )}

          {/* Refined Custom Additions */}
          {refinedCustomItems.length > 0 && (
            <div>
              <h2 className="text-zinc-100 font-semibold text-base mb-1">Refined Projects & Experiences</h2>
              <div className="space-y-4 mt-4">
                {refinedCustomItems.map((content, i) => {
                  return (
                    <RefinedItemCard
                      key={i}
                      label={`Custom Addition ${i + 1}`}
                      content={content}
                      approved={approvedCustomItems[i] ?? null}
                      onApprove={() =>
                        setApprovedCustomItems((prev) => ({ ...prev, [i]: true }))
                      }
                      onReject={() =>
                        setApprovedCustomItems((prev) => ({ ...prev, [i]: false }))
                      }
                    />
                  );
                })}
              </div>
            </div>
          )}

          {/* Template picker */}
          <TemplatePicker selected={selectedTemplate} onSelect={setSelectedTemplate} />

          {/* Generate button */}
          <div className="pb-4">
            {generateError && (
              <p className="text-red-400 text-sm mb-4 bg-red-500/10 border border-red-500/20 rounded-lg px-4 py-3 text-center">
                {generateError}
              </p>
            )}
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-full py-4 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-xl transition-all shadow-lg shadow-indigo-500/25 flex items-center justify-center gap-2 text-lg"
            >
              {isGenerating ? "Generating PDF..." : "Generate ATS-Optimized Resume ✨"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
